### ISSUE TITLE
Beamer slides (PDF) show linguistic examples in a overt table

### ISSUE THREAD

**Issue by CLRafaelR** [cysouw/pandoc-ling#1]
When I create [`Beamer`](https://ctan.org/pkg/beamer) slides including some linguistic examples produced via `pandoc-ling`, the output slides undesirably have these examples in a visible table, as shown in the following screen capture. This does not occur when I create a usual LaTeX-based documents (e.g. `article` class).

![image](https://user-images.githubusercontent.com/42314553/103971628-78561980-51ae-11eb-916c-6023e83b2312.png)

The behaviour is understandable since `pandoc-ling` is a table-environment-based glossing system, as you stated [in the manual](https://github.com/cysouw/pandoc-ling#the-basic-structure-of-a-linguistic-example). However, is there any good practice to make these tables invisible?

# Working example

Here I put an [Rmarkdown](https://rmarkdown.rstudio.com/) example with two subsidiary R packages, [`bookdown`](https://bookdown.org/) and [`officedown`](https://github.com/davidgohel/officedown). The contents are exactly same as pandoc's markdown, except what I wrote in YAML section.

```
---
title: "Pandoc-ling with Beamer"
author: "CLRR"
output: 
  bookdown::beamer_presentation2:
    latex_engine: xelatex
    keep_tex: TRUE
    keep_md: TRUE
    toc: TRUE
    number_sections: TRUE
    slide_level: 2
    pandoc_args:
      - --lua-filter=path-to/pandoc-ling/pandoc-ling.lua
  bookdown::pdf_document2:
    latex_engine: xelatex
    keep_tex: true
    keep_md: true
    pandoc_args:
      - --lua-filter=path-to/pandoc-ling/pandoc-ling.lua
  officedown::rdocx_document:
    mapstyles:
      Normal: ['First Paragraph']
    keep_md: TRUE
    pandoc_args:
      - --lua-filter=path-to/pandoc-ling/pandoc-ling.lua
always_allow_html: yes
link-citations: yes
---

## Basic example

::: ex
This is the most basic structure of a linguistic example. 
:::

## Multi-line example

::: {#id .ex formatGloss=false}

This is a multi-line example.
But that does not mean anything for the result
All these lines are simply treated as one paragraph.
They will become one example with one number.

:::

## Example with a preamble

:::ex
Preamble

This is an example with a preamble.
:::

## Multiple examples

:::ex
a. This is the first example.
b. This is the second.
a. The actual letters are not important, `pandoc-ling` will put them in order.

e. Empty lines are allowed between labelled lines
Subsequent lines are again treated as one sequential paragraph.
:::

## Examples with a judgement

:::ex
Throwing in a preamble for good measure

a. ^* This traditionally signals ungrammaticality.
b. ^? Question-marks indicate questionable grammaticality.
c. ^^whynot?^ But in principle any sequence can be used (here even in superscript).
d. However, such long sequences sometimes lead to undesirable effects in the layout.
:::

## Formatted interlinear example

::: {.ex formatGloss=true}
| Dutch (Germanic)
| Deze zin is in het nederlands.
| DEM sentence AUX in DET dutch.
| This sentence is dutch.
:::

## Cross-referenceing

::: {#test .ex}
This is a test
:::

@test is grammatical.

## Complex example

::: {.ex formatGloss=true}
Completely superfluous preamble, but it works ...

a. Mixing single line examples with interlinear examples.
a. This is of course highly unusal.
Just for this example, let's add some extra material in this example.

a.
| Dutch (Germanic) Note the grammaticality judgement!
| ^^:-)^ Deze zin is (dit\ is&nbsp;test) nederlands.
| DEM sentence AUX ~ dutch.
| This sentence is dutch.

b.
|
| Deze tweede zin heeft geen header.
| DEM second sentence have.3SG.PRES no header.
| This second sentence does not have a header.
:::
```

# Environment

pandoc-ling: [v1.1](https://github.com/cysouw/pandoc-ling/releases/tag/v1.1)
pandoc: v2.11.3.2
OS: Windows 10 x64 (build 19042)

**Comment by CLRafaelR** [comment]
In any case, I really appreciate your work of `pandoc-ling`. This is the greatest evolution in the creating/editing linguistic document!!

**Comment by cysouw** [comment]
I have never used `beamer` so I didn't catch this! I'll look into it. Basically my approach is to use the `class` info embedded by my filter. However, in Latex this is difficult, so I had to write separate Latex export. I hope this is not again necessary for beamer :-(. I'll have a look into this!

**Comment by cysouw** [comment]
Quick comment before I get to the lines: I first could not reproduce your output, until I realised that there is a change between pandoc 2.11.2 and 2.11.3 for the output of the new table format to latex. Now it works! That is great news!

**Comment by CLRafaelR** [comment]
Thank you for your work-around. Just a clarification: should I stop using pandoc 2.11.3 and revert to older version of pandoc?

**Comment by cysouw** [comment]
no no! 2.11.3 is much better! Your results were already better than I was getting here in the last weeks, so I was surprised to see your output. Then I found that I was a .point version behind :-)

**Comment by CLRafaelR** [comment]
I got it, and will keep using the latest version of pandoc! 👍🏻

**Comment by cysouw** [comment]
Seems to work now: I simply added `beamer` as an output with the same structure as for general latex. I have not checked it in much detail, but it seems to work best with `latexPackage: gb4e`

Please try it with the new release [v1.2](https://github.com/cysouw/pandoc-ling/releases/tag/v1.2) and tell me if it works for you

**Comment by CLRafaelR** [comment]
Brilliant!! What a breathtaking result...!

![image](https://user-images.githubusercontent.com/42314553/104042652-1a611a80-521e-11eb-971d-f006b249664a.png)

Again, I deeply appreciate your work and definitely recommend this filter to my colleagues!

Now I close this issue!
