### ISSUE TITLE
Question particle/marker `Q` is not rendered

### ISSUE THREAD

**Issue by CLRafaelR** [cysouw/pandoc-ling#12]
I use the latest pandoc-ling 2a1e55af5d976dab5557affdbee95fee05446ed4 as of July 4, 2022. I found that the question particle/marker `Q`, which is listed in [Leipzig Glossing Rules](https://www.eva.mpg.de/lingua/resources/glossing-rules.php#:~:text=Q,question%20particle/marker), is not rendered as shown below. Generally speaking, the current implementation may not render one-character abbreviations such as `Q`, `A`, `S`, `P`, `F`, `M` and so on.

![image](https://user-images.githubusercontent.com/42314553/177122215-5865c286-7f5a-4a0b-8649-8f82f76c3e31.png)

I think the issue should be resolved if `[%u%d][%u%d]` in l.447 and l.455 of `pandoc-ling.lua` is replaced with one `[%u%d]`. Could you mind pointing out whether any problem arises when we replace `[%u%d][%u%d]` with  `[%u%d]` or why `[%u%d][%u%d]` is originally used there?

https://github.com/cysouw/pandoc-ling/blob/2a1e55af5d976dab5557affdbee95fee05446ed4/pandoc-ling.lua#L447
https://github.com/cysouw/pandoc-ling/blob/2a1e55af5d976dab5557affdbee95fee05446ed4/pandoc-ling.lua#L455

# MWE

    ::: {#Q-particle .ex formatGloss=true}
    | **これは絵ですか？** `\\`{=latex}
    | Kore=wa e-desu-ka?
    | DEM=TOP picture-AFF.POL-Q
    | Is this a picture?
    :::
    
        ::: {#Q-particle .ex formatGloss=true}
        | **これは絵ですか？** `\\`{=latex}
        | Kore=wa e-desu-ka?
        | DEM=TOP picture-AFF.POL-Q
        | Is this a picture?
        :::

**Comment by CLRafaelR** [comment]
I tried replacing `[%u%d][%u%d]` with `[%u%d]` and successfully got the desirable output. 

![image](https://user-images.githubusercontent.com/42314553/177124777-c59deedf-bf11-48c5-b520-85f6b2481a2c.png)

**Comment by cysouw** [comment]
solved with #14
