### ISSUE TITLE
Blank header causes loss of indentation in Latex

### ISSUE THREAD

**Issue by speechchemistry** [cysouw/pandoc-ling#19]
Thank you for this very nicely designed tool. 

> There should always be four vertical lines (for header, source, gloss and translation, respectively), although the content after the first vertical line can be empty
(from https://cysouw.github.io/pandoc-ling/readme.html#interlinear-examples)

When I leave the content after the first verticle line empty e.g. 

```
:::ex
|
| Deze zin is in het nederlands.
| DEM sentence AUX in DET dutch.
| This sentence is dutch.
:::
```

I lose the indentation in Latex (the output is fine in `html` and `docx`). This is the Latex that is generated:

```
\ex. \label{ex2} 
  
  \gll Deze zin is in het nederlands. \\
       DEM sentence AUX in DET dutch. \\
  \glt This sentence is dutch.
```

That blank line means the indentation is lost. So a workaround is just to delete that blank line in the Latex file.

**Comment by cysouw** [comment]
I think I found the error. Please try downloading the file "pandoc-ling.lua" and use this filter instead of the one you are now using. Does it solve your error?

**Comment by speechchemistry** [comment]
Yes, that new version of `pandoc-ling.lua` solves the problem. Thanks very muchǃ
