### ISSUE TITLE
error running filter with recent pandoc

### ISSUE THREAD

**Issue by patrl** [cysouw/pandoc-ling#2]
Using the filter with pandoc version 2.11.3.2 results in the following error, potentially related to https://github.com/jgm/pandoc/issues/5331

```
Error running filter ./pandoc-ling.lua:
Could not get Meta value: Could not read value of key-value pair: Could not get MetaValue: Could not read list: Could not get Block value: Unknown block type: MetaBlocks
```

**Fix:** Changing line 83:

``` lua
    tmp[#tmp+1] = pandoc.MetaBlocks(pandoc.RawBlock("tex", s))
```

 to the following fixes the problem, and seems to produce an identical result (I haven't tested this thoroughly):

``` lua
    tmp[#tmp+1] = pandoc.RawBlock("tex", s)
```

**Comment by cysouw** [comment]
I just tried it with 2.11.4 and I don't get any errors. Could you please try again with that newer Pandoc version?

**Comment by patrl** [comment]
Yes, this seems to be fixed in the latest pandoc release.
