### ISSUE TITLE
One-line examples with a judgement are unprocessible when producing an HTML file

### ISSUE THREAD

**Issue by CLRafaelR** [cysouw/pandoc-ling#3]
I am trying to produce an HTML file which contains one-line examples with a judgement. If I correctly understand, the following markdown syntax will work:

```markdown
::: ex
^* This traditionally signals ungrammaticality.
:::
```

However, pandoc throws an error on lua when processing the markdown file, as follows:

```bash
Error running filter configuration/pandoc-ling/pandoc-ling.lua:
configuration/pandoc-ling/pandoc-ling.lua:607: attempt to index a nil value (field '?')
stack traceback:
	configuration/pandoc-ling/pandoc-ling.lua:607: in function 'pandocMakeSingle'
	configuration/pandoc-ling/pandoc-ling.lua:527: in function 'pandocMakeExample'
	configuration/pandoc-ling/pandoc-ling.lua:256: in function 'processDiv'
Error: pandoc document conversion failed with error 83
```

The problem looks similar to the issue on the following link, but I cannot work around by myself since I am not familiar with lua...
https://stackoverflow.com/q/12153537/10215301

What am I missing...?

# MWE

Here I put an [Rmarkdown](https://rmarkdown.rstudio.com/) example with its subsidiary R packages, [`bookdown`](https://bookdown.org/). The contents are exactly same as pandoc's markdown, except what I wrote in YAML section.

    ---
    author: Masataka OGAWA
    title: Using pandoc-ling for HTML
    
    output: 
      bookdown::html_document2:
        pandoc_args:
          - --lua-filter=configuration/pandoc-ling/pandoc-ling.lua
    
      ## No problem with pdf-producing
      bookdown::pdf_document2:
        pandoc_args:
          - --lua-filter=configuration/pandoc-ling/pandoc-ling.lua
    ---
    
    These two examples throw an error when I produce an HTML file:
    
    ```
    Error running filter configuration/pandoc-ling/pandoc-ling.lua:
    configuration/pandoc-ling/pandoc-ling.lua:607: attempt to index a nil value (field '?')
    stack traceback:
    	configuration/pandoc-ling/pandoc-ling.lua:607: in function 'pandocMakeSingle'
    	configuration/pandoc-ling/pandoc-ling.lua:527: in function 'pandocMakeExample'
    	configuration/pandoc-ling/pandoc-ling.lua:256: in function 'processDiv'
    Error: pandoc document conversion failed with error 83
    ```
    
    ::: ex
    ^* This traditionally signals ungrammaticality.
    :::
    
    ::: ex
    a. ^* This traditionally signals ungrammaticality.
    :::
    
        

Note but that I can produce a PDF file without any problem with the Rmd file above, as shown in the following screen capture.

![image](https://user-images.githubusercontent.com/42314553/107216957-d6e21200-6a50-11eb-8722-2c9bc5f79179.png)

# Environment

Environment
pandoc-ling: v1.4
pandoc: v2.11.4
OS: Windows 10 x64 (build 19042)

**Comment by cysouw** [comment]
You found a bug! It's fixed now in the master branch, so please download it from there. The next release will come later.

**Comment by CLRafaelR** [comment]
I always appreciate your quick response and now I confirm that I can get the desirable HTML! 
Thank you so much and I close this issue!
