### ISSUE TITLE
Escape meta characters of LaTeX in "judgeOffset" to avoid the compilation failure

### ISSUE THREAD

**Issue by CLRafaelR** [cysouw/pandoc-ling#4]
I found that PDF compilation via LaTeX halts when `judgeMax`, the character/word used for the grammaticality/acceptability judgement whose number of characters are the largest in the `ex` environment, contains one of the LaTeX's meta-characters such as `#`, `%` or `&`. So, the following two markdown examples are not properly processed in the compilation procedure and throw an error: `! Illegal parameter number in definition of \@jwidth.`

```markdown
::: {.ex #grammaticality-judgement}
^# I'm not sure this is grammatical.
:::
```
or
```markdown
::: {.ex #grammaticality-judgement}
a. ^# I'm not sure this is grammatical.
a. This is grammatical.
:::
```

I suspect that [the line in `texMakeGb4e` function](https://github.com/cysouw/pandoc-ling/blob/95bf37e064228d8faac9d42cb8ad2582d185e02c/pandoc-ling.lua#L1189) and [the line in `texMakeLangsci` function](https://github.com/cysouw/pandoc-ling/blob/95bf37e064228d8faac9d42cb8ad2582d185e02c/pandoc-ling.lua#L1290) render the characters like `#`, `%` or `&` to LaTeX as they are (i.e. without escaping them) and that this causes the above-mentioned error.

Those lines can be replaced with the following lua command (I verified this works in my environment):

```lua
local judgeOffset = "\\judgewidth{"..string.gsub(pandoc.utils.stringify(judgeMax), "([#$%&_{}~^])", "\\%1").."}"
```

Would you mind considering and verifying this patch? 

# Environment

pandoc-ling: [the latest version](https://github.com/cysouw/pandoc-ling/commit/95bf37e064228d8faac9d42cb8ad2582d185e02c#diff-548756ae6618dbb76885a661249172cca820d1e8b7fc7242ce826d177656bbc8) as of 2021/02/24
pandoc: v2.11.4
OS: Windows 10 x64 (build 19042)

**Comment by cysouw** [comment]
Good catch! The error does not occur with `linguex`, so that might help until I have managed to fix this.

**Comment by cysouw** [comment]
I fixed it using your proposal, thx @CLRafaelR!

**Comment by CLRafaelR** [comment]
Yes, the problem occurred with (langsci-)gb4e and I had to mentioned that more implicitly... Thank you for the adaptation of the patch!

**Comment by cysouw** [comment]
I also added a new "lazy" example-coding possibility, in which you can make subentries (with letters) by just typing dashed (markdown lists). It will insert the letters anyway :-)
