### ISSUE TITLE
header-includes in the YAML header causes an error when exporting to LaTeX or pdf

### ISSUE THREAD

**Issue by tpellard** [cysouw/pandoc-ling#5]
When the YAML header contains `header-includes`, pandoc (2.13) cannot export to LaTeX or to pdf.
Exporting to docx works as expected.

Here is a minimal example and the command line run:

```
---
title: Testing pandoc-ling
header-includes: |
  \usepackage{hyperref}
---

# This is a test

::: ex
This is the most basic structure of a linguistic example.
:::
```
`pandoc pandoc-ling_test.md -o pandoc-ling_test.tex --lua-filter pandoc-ling.lua`

**Comment by cysouw** [comment]
I find the metadata handling of Pandoc confusing :-). But with a minimal change your problem has gone away. Please grab the latest commit for a working version.
